version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/emotion_diary
permissions:
  - object: /home/ubuntu/emotion_diary/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: /server/scripts/deploy.sh
      timeout: 60
      runas: ubuntu